"""
Structured Ember platform manual for popup AI retrieval.

This is intentionally static and human-curated. It reflects the current app
surface from App routes, navigation config, representative page code, and
existing docs. When a workflow or module appears partial, the note says so
instead of inventing behavior.
"""

from __future__ import annotations

from typing import Dict, List


PLATFORM_MANUAL: List[Dict[str, object]] = [
    {
        "key": "dashboard",
        "display_name": "Dashboard",
        "routes": ["/", "/enhanced-dashboard", "/legacy-dashboard"],
        "aliases": ["dashboard", "home", "overview", "landing page", "main dashboard"],
        "who_uses_it": "All authenticated users",
        "purpose": "High-level caseload, alerts, metrics, and jump-off point into daily work.",
        "use_when": "Use first thing in the morning or when you need a quick cross-platform status check.",
        "required_or_useful_data": ["Caseload counts", "alerts", "high-level client status", "links into Smart Daily and client work"],
        "step_by_step": [
            "Open Dashboard to review overall caseload status and alert cards.",
            "Check which cards or widgets indicate overdue, active, or high-priority work.",
            "Jump from Dashboard into Smart Daily, Case Management, or another module based on the issue."
        ],
        "workflows": ["Daily case manager morning workflow", "Supervisor review workflow"],
        "related_modules": ["smart_daily", "case_management", "messages", "supervisor_dashboard"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Dashboard itself is overview-only; document client work in Documentation or the relevant client module.",
        "common_mistakes": ["Treating Dashboard as the place to save documentation", "Stopping at the overview without moving work into Smart Daily or client modules"],
        "known_limitations": ["Dashboard is an overview, not the task execution surface."],
        "caution_notes": ["Do not claim anything was updated from Dashboard unless another module or tool confirms it."],
        "example_questions": ["What should I check every morning?", "Where do I start my day in Ember?"],
    },
    {
        "key": "smart_daily",
        "display_name": "Smart Daily",
        "routes": ["/smart-dashboard"],
        "aliases": ["smart daily", "tasks", "task list", "reminders", "daily queue", "today", "follow-up list"],
        "who_uses_it": "All authenticated users",
        "purpose": "Primary task and reminder command center tied to daily follow-up.",
        "use_when": "Use when prioritizing the day, creating follow-up tasks, or checking what is due next.",
        "required_or_useful_data": ["Selected client when doing client-linked task work", "task title", "details", "task type", "due date", "priority"],
        "step_by_step": [
            "Open Smart Daily to review today's tasks, reminders, and priority items.",
            "Use client binding when the task belongs to a specific client.",
            "Create or update reminders for deadlines, appointments, insurance checks, legal dates, housing calls, or documentation follow-up.",
            "Return after completing work to close or update the task state."
        ],
        "workflows": ["Daily case manager morning workflow", "Full new client intake", "Housing referral workflow", "Legal or court update workflow"],
        "related_modules": ["dashboard", "admissions", "documentation", "legal", "benefits", "medical", "treatment_plan"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Use Smart Daily for reminders and action items, not narrative case notes.",
        "common_mistakes": ["Leaving follow-up only in notes instead of creating a reminder", "Creating tasks without binding the correct client when client context is needed"],
        "known_limitations": ["No separate top-level reminders route exists; reminders and tasks live through Smart Daily."],
        "caution_notes": ["Do not say a reminder exists unless it was actually created or is visible in Smart Daily."],
        "example_questions": ["How do I set up follow-up tasks?", "What belongs in Smart Daily?"],
    },
    {
        "key": "case_management",
        "display_name": "Case Management",
        "routes": ["/case-management"],
        "aliases": ["case management", "caseload", "client list", "client profile list", "clients"],
        "who_uses_it": "All authenticated users",
        "purpose": "Caseload management, client creation and editing, and initial client-need review.",
        "use_when": "Use after intake or whenever you need to review or update core client information.",
        "required_or_useful_data": ["Client demographics", "housing status", "medical needs", "legal needs", "benefits needs", "employment needs"],
        "step_by_step": [
            "Open Case Management to review the current caseload or search for a client.",
            "Open an existing client or create/update a client profile as appropriate.",
            "Review immediate needs and risk indicators before moving into specialty modules."
        ],
        "workflows": ["Full new client intake", "Client profile update", "Discharge planning"],
        "related_modules": ["client_dashboard", "admissions", "documentation", "housing", "benefits", "legal", "medical", "jobs", "resume"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Core profile fields and operational status belong here; detailed notes belong in Documentation.",
        "common_mistakes": ["Using Case Management as a substitute for narrative documentation", "Skipping client profile review before sending work into specialty modules"],
        "known_limitations": ["Some deeper client work happens in Client Dashboard or specialty modules, not on the main caseload list."],
        "caution_notes": ["If the popup has no live selected client, tell the user to open or select the client first."],
        "example_questions": ["How do I update a client profile?", "Where do I see my caseload?"],
    },
    {
        "key": "client_dashboard",
        "display_name": "Client Dashboard",
        "routes": ["/client/:clientId", "/case-management/:clientId"],
        "aliases": ["client dashboard", "client profile", "client page", "selected client", "client detail"],
        "who_uses_it": "All authenticated users",
        "purpose": "Client-specific view that links the selected client to housing, messages, documents, and other care areas.",
        "use_when": "Use when you are working on one client across several domains.",
        "required_or_useful_data": ["Selected client", "client-level housing, documents, messaging, and status data"],
        "step_by_step": [
            "Open the client from Case Management or a deep link.",
            "Review the client-specific tabs and summary areas.",
            "Use the client-linked shortcuts to move into housing, messages, or related client work."
        ],
        "workflows": ["Client profile update", "Discharge planning", "Housing referral workflow"],
        "related_modules": ["case_management", "housing", "messages", "documentation"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Use the client view to locate context; narrative and formal documentation still belong in Documentation or the relevant form-driven module.",
        "common_mistakes": ["Assuming every client update is saved from the dashboard alone"],
        "known_limitations": ["Deep route; not a primary navigation item."],
        "caution_notes": ["When the assistant lacks client selection, it should explain the workflow generally and say a client must be opened first for client-specific actions."],
        "example_questions": ["How do I work from a specific client page?", "Where do I open a client’s housing info?"],
    },
    {
        "key": "admissions",
        "display_name": "Admissions",
        "routes": ["/admissions", "/admissions/new", "/admissions/:client_id", "/admissions/:client_id/forms/:form_key"],
        "aliases": ["admissions", "intake", "new client", "admission packet", "packet", "forms", "face sheet"],
        "who_uses_it": "All authenticated users",
        "purpose": "New-client intake, admission packets, shared-profile seeding, and form completion.",
        "use_when": "Use when starting a new admission or completing required intake forms.",
        "required_or_useful_data": ["Client demographics", "contacts", "emergency contact", "insurance", "consents", "ROI needs", "referral source", "shared profile data"],
        "step_by_step": [
            "Open Admissions to start a new full admission or open an existing packet.",
            "Choose an existing client or create a new client in Admissions.",
            "Complete packet forms and review shared profile autofill carefully.",
            "Use the packet-level Smart Daily suggestions for missing or overdue follow-up when available."
        ],
        "workflows": ["Full new client intake", "Benefits or insurance intake review", "Medical or legal intake flag review"],
        "related_modules": ["case_management", "documentation", "benefits", "medical", "legal", "smart_daily"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Intake forms, packet data, insurance details, consents, and shared profile fields belong here.",
        "common_mistakes": ["Assuming Quick Intake replaced full Admissions", "Overwriting manual edits without checking shared profile behavior", "Leaving follow-up work in the packet without adding Smart Daily tasks"],
        "known_limitations": ["Admissions roadmap references future Smart Daily and financial coordination enhancements; some items are still marked upcoming."],
        "caution_notes": ["Respect manual edits in admissions autofill. Do not claim a packet or form was saved unless the app confirms it."],
        "example_questions": ["How do I do a full intake?", "Where do I put insurance during intake?"],
    },
    {
        "key": "documentation",
        "display_name": "Documentation",
        "routes": ["/documentation"],
        "aliases": ["documentation", "notes", "documents", "cm note", "progress note", "court note", "group note", "discharge note"],
        "who_uses_it": "All authenticated users",
        "purpose": "Notes and documents command center for client-facing and operational documentation.",
        "use_when": "Use when writing notes, saving documents, or choosing a note type such as Court, Housing, Legal, Benefits, Group, or FMLA.",
        "required_or_useful_data": ["Selected client", "note type", "note body", "document metadata", "template guidance"],
        "step_by_step": [
            "Open Documentation and select the client first.",
            "Choose note or document mode and the correct note type.",
            "Use the template guidance if available, then save the note or document in the appropriate category."
        ],
        "workflows": ["Initial CM note", "Group session documentation", "Legal or court update workflow", "Discharge planning"],
        "related_modules": ["admissions", "treatment_plan", "groups", "legal", "housing", "benefits", "fmla"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Initial CM notes, progress notes, court updates, group notes, housing updates, employment notes, legal notes, discharge notes, referral notes, and FMLA documentation.",
        "common_mistakes": ["Trying to save documentation before selecting a client", "Using the wrong note type", "Putting reminders into notes without also using Smart Daily"],
        "known_limitations": ["Documentation relies on selected client context; the assistant should say so when that context is missing."],
        "caution_notes": ["Use Case Manager Playbook or internal template guidance when responding to documentation questions."],
        "example_questions": ["Where do I document a court update?", "How do I write an initial CM note?"],
    },
    {
        "key": "treatment_plan",
        "display_name": "Treatment Plan",
        "routes": ["/treatment-plan"],
        "aliases": ["treatment plan", "plan", "goals", "objectives", "interventions", "aftercare plan"],
        "who_uses_it": "All authenticated users",
        "purpose": "Structured treatment planning with goals, problems, objectives, interventions, and aftercare.",
        "use_when": "Use after needs are identified and a client plan should be formalized or reviewed.",
        "required_or_useful_data": ["Selected client", "operational needs", "problems", "goals", "objectives", "interventions", "aftercare plan", "completion criteria"],
        "step_by_step": [
            "Open Treatment Plan and select the client.",
            "Review active or draft plans.",
            "Create or update goals, objectives, interventions, and aftercare sections, then approve the plan if appropriate."
        ],
        "workflows": ["Treatment plan creation", "Discharge planning", "Daily case manager morning workflow"],
        "related_modules": ["documentation", "case_management", "smart_daily", "groups"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Needs, goals, objectives, interventions, aftercare plan, completion criteria, and plan review updates.",
        "common_mistakes": ["Treating Treatment Plan as the note storage location instead of the structured planning surface"],
        "known_limitations": ["The module supports draft and active states; use the status shown in the UI instead of assuming activation."],
        "caution_notes": ["If the AI mentions a treatment plan, it should also tell the user where the supporting note belongs if narrative documentation is needed."],
        "example_questions": ["How do I create a treatment plan?", "Where do I update goals and interventions?"],
    },
    {
        "key": "groups",
        "display_name": "Groups",
        "routes": ["/groups", "/groups/sessions/:sessionId"],
        "aliases": ["groups", "group note", "group session", "facilitation", "curriculum", "playlist"],
        "who_uses_it": "All authenticated users",
        "purpose": "Group facilitation workflow for topics, discussions, activities, and sessions.",
        "use_when": "Use when preparing or documenting group sessions.",
        "required_or_useful_data": ["Group title", "description", "key points", "discussion questions", "activity", "writing prompt", "facilitator tips"],
        "step_by_step": [
            "Open Groups to create or review group content or sessions.",
            "Build the session structure with topic, key points, discussion prompts, and activities.",
            "Use Documentation if a narrative group note also needs to be saved for a client or session."
        ],
        "workflows": ["Group session documentation"],
        "related_modules": ["documentation", "treatment_plan"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Group session setup belongs here; resulting narrative notes can be mirrored in Documentation when needed.",
        "common_mistakes": ["Assuming group setup automatically creates all narrative documentation"],
        "known_limitations": ["The page clearly supports content and session structure; client-specific note persistence should still be verified in Documentation if needed."],
        "caution_notes": ["If the workflow needs an actual client note, the assistant should route the user back to Documentation."],
        "example_questions": ["How do I write group notes?", "How do I set up a group session?"],
    },
    {
        "key": "ur",
        "display_name": "Utilization Review",
        "routes": ["/ur"],
        "aliases": ["ur", "utilization review", "authorization", "coverage", "placement", "reviewer", "medical necessity"],
        "who_uses_it": "All authenticated users working UR cases",
        "purpose": "Utilization Review command center for authorization, coverage, placement, reviewer communication, and deadlines.",
        "use_when": "Use when managing authorizations, continued stay review, denial risk, or payer communication.",
        "required_or_useful_data": ["Selected client", "payer", "program", "level of care", "authorization detail", "reviewer info", "deadlines", "clinical justification summary"],
        "step_by_step": [
            "Open UR and select the case-management client.",
            "Review the workflow coach and current step.",
            "Capture coverage, placement, authorization, reviewer communication, deadlines, and medical necessity summary."
        ],
        "workflows": ["Utilization Review workflow"],
        "related_modules": ["documentation", "medical", "benefits", "smart_daily"],
        "role_restrictions": "All authenticated users with UR responsibilities",
        "what_to_document": "Authorization status, payer detail, reviewer contact, deadlines, and clinical justification summary.",
        "common_mistakes": ["Answering UR questions generically without mentioning authorization fields, reviewer communication, or deadlines"],
        "known_limitations": ["The workflow coach is visible in the page code, but downstream integrations should be treated as module-specific rather than assumed platform-wide."],
        "caution_notes": ["The assistant should not present UR as generic insurance advice; it should describe the actual UR workflow surface in Ember."],
        "example_questions": ["How do I use the UR module?", "Where do I track authorization deadlines?"],
    },
    {
        "key": "housing",
        "display_name": "Housing",
        "routes": ["/housing", "/housing/case-manager", "/housing/test"],
        "aliases": ["housing", "housing search", "placement", "housing referral", "case manager housing"],
        "who_uses_it": "All authenticated users",
        "purpose": "Housing search and case-manager housing workflow.",
        "use_when": "Use when coordinating placement, searching housing, or tracking housing referral work.",
        "required_or_useful_data": ["Search terms", "location", "client housing need", "referral notes", "site visit or housing link"],
        "step_by_step": [
            "Open Housing to run searches or open case-manager housing tools.",
            "Search by location and client need.",
            "Use client-linked housing actions and document the outcome in Documentation, then add follow-up in Smart Daily."
        ],
        "workflows": ["Housing referral workflow", "Discharge planning"],
        "related_modules": ["client_dashboard", "sober_living", "sober_living_directory", "documentation", "smart_daily"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Housing outreach, referrals, placement status, and next steps should be documented outside the search results themselves if narrative documentation is needed.",
        "common_mistakes": ["Stopping at the search results without documenting the outreach or creating follow-up tasks"],
        "known_limitations": ["`/housing/test` is a test route and should not be recommended as normal workflow."],
        "caution_notes": ["Keep `/housing` intact; do not repurpose it when describing sober living or directory work."],
        "example_questions": ["How do I coordinate housing?", "Where do I put housing follow-up?"],
    },
    {
        "key": "sober_living",
        "display_name": "Sober Living",
        "routes": ["/sober-living", "/sober-living/:houseId"],
        "aliases": ["sober living", "house management", "beds", "residents", "ua test", "passes"],
        "who_uses_it": "All authenticated users working sober-living operations",
        "purpose": "Sober living house records, resident operations, capacity, and house management.",
        "use_when": "Use for house setup, resident placement, or sober-living operational tracking.",
        "required_or_useful_data": ["House details", "capacity", "certification", "funding notes", "resident data", "bed assignments"],
        "step_by_step": [
            "Open Sober Living to manage house records or open a specific house.",
            "Review house details, capacity, certification, and funding notes.",
            "Use the house detail route for resident, bed, payment, incident, pass, and chore actions where applicable."
        ],
        "workflows": ["Sober living coordination", "Housing referral workflow", "Discharge planning"],
        "related_modules": ["housing", "sober_living_directory", "documentation", "smart_daily"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Operational house data belongs here; client-facing notes and coordination summaries should still be documented where needed.",
        "common_mistakes": ["Using Sober Living when the need is actually external sober-living search rather than house operations"],
        "known_limitations": ["Some sober-living work is operational house management rather than case-manager referral guidance; use the directory when the need is provider research."],
        "caution_notes": ["If the user asks about placement research, the closest available place may be Sober Living Directory rather than the house-management module."],
        "example_questions": ["How do I coordinate sober living placement?", "Where do I manage a sober living house?"],
    },
    {
        "key": "sober_living_directory",
        "display_name": "Sober Living Directory",
        "routes": ["/sober-living-directory", "/sober-living-directory/discovery", "/sober-living-directory/review", "/sober-living-directory/:listingId"],
        "aliases": ["sober directory", "sober living directory", "directory", "discovery", "review", "listing"],
        "who_uses_it": "All authenticated users",
        "purpose": "Manual-first sober-living search and review tool with saved and live external results.",
        "use_when": "Use when researching or comparing sober-living options.",
        "required_or_useful_data": ["Location", "zip", "certification filter", "notes about MAT, rent, funding, or call outcomes"],
        "step_by_step": [
            "Open the directory search page and enter location or zip filters.",
            "Review saved directory results and live external results.",
            "Open listing detail, discovery, or review pages as needed, then document outreach and create follow-up tasks elsewhere."
        ],
        "workflows": ["Sober living coordination", "Housing referral workflow"],
        "related_modules": ["housing", "sober_living", "services", "documentation", "smart_daily"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Case-manager notes, call outcomes, and rent or funding details should be captured in the note areas and mirrored in Documentation if needed for the client record.",
        "common_mistakes": ["Inventing that discovery or scheduler controls are stable if the page shows availability errors or auth failures"],
        "known_limitations": ["Discovery controls and scheduler sections show explicit unavailable or auth-failure states in the code; assistant should acknowledge that if relevant."],
        "caution_notes": ["Describe this as a research and coordination surface, not a guaranteed placement engine."],
        "example_questions": ["How do I research sober living options?", "What is the discovery page for?"],
    },
    {
        "key": "benefits",
        "display_name": "Benefits",
        "routes": ["/benefits"],
        "aliases": ["benefits", "medi-cal", "medical insurance", "dpss", "calfresh", "gr", "general relief", "ssi", "ssdi"],
        "who_uses_it": "All authenticated users",
        "purpose": "Benefits and support management, including insurance and public-benefit coordination.",
        "use_when": "Use when tracking or reviewing benefits, supporting documents, or insurance-related client work.",
        "required_or_useful_data": ["Selected client", "benefit type", "income", "work limitations", "supporting documents", "insurance details"],
        "step_by_step": [
            "Open Benefits and select the client first.",
            "Review benefit-specific fields, supporting documents, and client status.",
            "Use Admissions as supporting context if the question is about intake-time insurance data."
        ],
        "workflows": ["Benefits and Medi-Cal workflow", "Medical appointment coordination", "Full new client intake"],
        "related_modules": ["admissions", "medical", "documentation", "smart_daily"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Benefits status, insurance support documents, benefit application details, and follow-up actions.",
        "common_mistakes": ["Answering benefits questions without telling the user to select a client first", "Leaving insurance follow-up out of Smart Daily"],
        "known_limitations": ["The assistant should distinguish Benefits from Billing; Billing is organizational plan management, not client benefits work."],
        "caution_notes": ["Do not invent benefit approval or coverage status. If insurance data is unavailable, say what source was checked."],
        "example_questions": ["How do I use Benefits?", "Where do I put Medi-Cal info?"],
    },
    {
        "key": "medical",
        "display_name": "Medical",
        "routes": ["/medical"],
        "aliases": ["medical", "appointment", "pcp", "dental", "psychiatry", "therapy", "provider"],
        "who_uses_it": "All authenticated users",
        "purpose": "Medical provider and appointment coordination.",
        "use_when": "Use for provider search, appointment coordination, or tracking medical needs tied to a client.",
        "required_or_useful_data": ["Selected client", "medical need", "provider search parameters", "appointment details"],
        "step_by_step": [
            "Open Medical and select the client first.",
            "Load medical providers or appointments using the client context and relevant search filters.",
            "Document outcomes and track appointment follow-up in Smart Daily if needed."
        ],
        "workflows": ["Medical appointment coordination", "Full new client intake"],
        "related_modules": ["benefits", "documentation", "smart_daily", "case_management"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Provider coordination, appointment status, and any client-facing medical follow-up.",
        "common_mistakes": ["Presenting medical coordination as clinical advice", "Skipping the client selection requirement"],
        "known_limitations": ["The assistant should keep this operational: provider search and appointments, not diagnosis or treatment decisions."],
        "caution_notes": ["No medical diagnosis or treatment advice."],
        "example_questions": ["How do I coordinate a medical appointment?", "Where do I track PCP or psychiatry follow-up?"],
    },
    {
        "key": "legal",
        "display_name": "Legal",
        "routes": ["/legal"],
        "aliases": ["legal", "court", "probation", "parole", "charges", "legal update", "proof letter"],
        "who_uses_it": "All authenticated users",
        "purpose": "Legal case coordination, court-related work, and legal file support.",
        "use_when": "Use when updating court status, legal tasks, or legal-file attachments for a selected client.",
        "required_or_useful_data": ["Selected client", "charges", "court dates", "legal files", "status details"],
        "step_by_step": [
            "Open Legal and select the client first.",
            "Review or update legal details, charges, or supporting files.",
            "Then document the narrative update in Documentation and add any due-date follow-up to Smart Daily."
        ],
        "workflows": ["Legal, probation, or court update workflow", "Discharge planning"],
        "related_modules": ["documentation", "smart_daily", "case_management"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Court or legal status, attached notices or motions, related follow-up steps, and deadlines.",
        "common_mistakes": ["Giving only generic legal advice instead of pointing to the Legal module plus Documentation and Smart Daily"],
        "known_limitations": ["The assistant should present Legal as coordination and tracking, not legal authority."],
        "caution_notes": ["No definitive legal advice. Recommend escalation to counsel or supervisor when needed."],
        "example_questions": ["Where do I document a court update?", "How do I track probation follow-up?"],
    },
    {
        "key": "fmla",
        "display_name": "FMLA",
        "routes": ["/fmla"],
        "aliases": ["fmla", "leave", "std", "disability leave", "return to work", "workflow bucket"],
        "who_uses_it": "All authenticated users working FMLA or leave cases",
        "purpose": "Leave paperwork, workflow stages, and employer or benefits tracking.",
        "use_when": "Use for FMLA, STD, denial, approval, or return-to-work tracking.",
        "required_or_useful_data": ["Workflow stage", "workflow bucket", "case details", "employer data", "deadlines", "forms"],
        "step_by_step": [
            "Open FMLA to review the case workflow stage and bucket.",
            "Review progress indicators and case status.",
            "Track missing paperwork, deadlines, and return-to-work steps, then use Smart Daily for follow-up."
        ],
        "workflows": ["FMLA tracking workflow"],
        "related_modules": ["documentation", "benefits", "smart_daily"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "FMLA or STD status, deadlines, paperwork progress, and next actions.",
        "common_mistakes": ["Confusing FMLA case tracking with organizational billing or HR settings"],
        "known_limitations": ["The page shows workflow snapshot logic; the assistant should treat it as a tracking module rather than an external filing service."],
        "caution_notes": ["If exact employer-policy interpretation is needed, say it depends on employer or legal review."],
        "example_questions": ["How do I use FMLA?", "Where do I track leave paperwork deadlines?"],
    },
    {
        "key": "messages",
        "display_name": "Messages",
        "routes": ["/messages"],
        "aliases": ["messages", "messenger", "thread", "staff message", "direct message", "conversation"],
        "who_uses_it": "All authenticated users",
        "purpose": "Internal messaging and thread creation.",
        "use_when": "Use when starting or continuing staff communication related to client coordination or operational follow-up.",
        "required_or_useful_data": ["Thread title", "purpose", "recipient", "first message"],
        "step_by_step": [
            "Open Messages to view threads or create a new one.",
            "Choose the recipient or case manager as needed.",
            "Set an optional title or purpose and send the first message."
        ],
        "workflows": ["Daily case manager morning workflow", "Supervisor review workflow", "Admin and team workflow"],
        "related_modules": ["dashboard", "smart_daily", "client_dashboard"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Messages are for communication; formal client documentation should still go in Documentation.",
        "common_mistakes": ["Using internal messages as the only record for client-facing work that should also be documented"],
        "known_limitations": ["Messaging is an internal collaboration surface, not a note repository."],
        "caution_notes": ["Keep protected client details aligned with policy and minimum-necessary use."],
        "example_questions": ["How do I message another staff member about a client?", "Where do I start a thread?"],
    },
    {
        "key": "resume",
        "display_name": "Resume Builder",
        "routes": ["/resume"],
        "aliases": ["resume", "resume builder", "employment profile", "work history", "skills profile"],
        "who_uses_it": "All authenticated users supporting employment work",
        "purpose": "Resume building and employment profile management for a client.",
        "use_when": "Use when preparing a client’s resume or employment profile.",
        "required_or_useful_data": ["Selected client", "career objective", "work history", "skills", "resume AI instructions"],
        "step_by_step": [
            "Open Resume and select the client.",
            "Review or build the employment profile.",
            "Generate, save, or review resumes based on the profile."
        ],
        "workflows": ["Employment and reentry workflow"],
        "related_modules": ["jobs", "case_management", "documentation"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Employment profile data belongs here; narrative case notes about employment planning can go in Documentation if needed.",
        "common_mistakes": ["Using Resume when the user really needs the Jobs module for job search actions"],
        "known_limitations": ["There are multiple resume-related page files in the repo, but `/resume` is the active routed page."],
        "caution_notes": ["Keep resume work grounded in the selected client’s employment profile."],
        "example_questions": ["How do I build a resume for a client?", "Where do I save employment profile data?"],
    },
    {
        "key": "jobs",
        "display_name": "Jobs",
        "routes": ["/jobs"],
        "aliases": ["jobs", "job search", "employment", "reentry employment", "work search"],
        "who_uses_it": "All authenticated users supporting employment goals",
        "purpose": "Job-search support tied to a selected client.",
        "use_when": "Use when searching for work opportunities or guiding employment follow-up.",
        "required_or_useful_data": ["Selected client", "job terms", "location", "employment goals"],
        "step_by_step": [
            "Open Jobs and select the client first.",
            "Enter job search terms and location.",
            "Use the results and any site guidance to continue the search, then track follow-up elsewhere."
        ],
        "workflows": ["Employment and reentry workflow"],
        "related_modules": ["resume", "case_management", "smart_daily"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Employment goals and follow-up actions can be documented in Documentation or Smart Daily as needed.",
        "common_mistakes": ["Inventing fully automated job-search support when the page itself says some tools are coming soon"],
        "known_limitations": ["The page explicitly says some tools to support the full job-search process are coming soon."],
        "caution_notes": ["If a capability is incomplete, say the closest available place in Ember is Jobs plus Resume plus Smart Daily follow-up."],
        "example_questions": ["How do I use Jobs?", "How do I support employment planning in Ember?"],
    },
    {
        "key": "team_management",
        "display_name": "Team Management",
        "routes": ["/team"],
        "aliases": ["team", "team management", "invite staff", "assign roles", "staff management"],
        "who_uses_it": "Admin users",
        "purpose": "Invite staff and manage team membership or roles.",
        "use_when": "Use when an admin needs to add staff or manage team access.",
        "required_or_useful_data": ["Staff email", "full name", "role"],
        "step_by_step": [
            "Open Team Management as an admin.",
            "Enter the staff member’s email and name.",
            "Use the available team controls to invite or manage staff."
        ],
        "workflows": ["Admin and team workflow"],
        "related_modules": ["settings", "supervisor_dashboard", "support"],
        "role_restrictions": "Admin only",
        "what_to_document": "Administrative team changes belong in admin records, not client notes.",
        "common_mistakes": ["Recommending Team Management to non-admin users"],
        "known_limitations": ["Access is role-gated."],
        "caution_notes": ["The popup assistant must hide this from normal users."],
        "example_questions": ["How do I invite staff?", "Where do I manage my team?"],
    },
    {
        "key": "supervisor_dashboard",
        "display_name": "Supervisor Dashboard",
        "routes": ["/supervisor-dashboard"],
        "aliases": ["supervisor", "supervisor dashboard", "team oversight", "staff workload"],
        "who_uses_it": "Admin users",
        "purpose": "Supervisor oversight surface for team metrics and review.",
        "use_when": "Use when reviewing staff workload or team-level metrics.",
        "required_or_useful_data": ["Supervisor overview metrics", "team management context"],
        "step_by_step": [
            "Open Supervisor Dashboard as an admin.",
            "Review team and workload metrics.",
            "Move into Team Management or Smart Daily depending on whether the issue is staffing or task flow."
        ],
        "workflows": ["Supervisor review workflow"],
        "related_modules": ["team_management", "smart_daily", "dashboard"],
        "role_restrictions": "Admin only",
        "what_to_document": "Supervisor observations usually belong in internal processes, not client notes, unless they lead to specific client actions elsewhere.",
        "common_mistakes": ["Treating Supervisor Dashboard as available to standard case managers"],
        "known_limitations": ["Role-gated route."],
        "caution_notes": ["Hide for non-admins."],
        "example_questions": ["How do I review staff workload?", "Where do supervisors start?"],
    },
    {
        "key": "owner_cockpit",
        "display_name": "Owner Cockpit",
        "routes": ["/owner"],
        "aliases": ["owner cockpit", "owner", "platform operations", "hq", "activity center"],
        "who_uses_it": "Platform super-admin users",
        "purpose": "Platform-owner command center for company-level analytics and owner actions.",
        "use_when": "Use only for platform-level oversight, not ordinary client work.",
        "required_or_useful_data": ["Owner analytics", "safe owner/admin activity feed", "support queue context"],
        "step_by_step": [
            "Open Owner Cockpit if you are a platform super-admin.",
            "Use it for platform operations, safe activity review, support queue review, or company-level visibility."
        ],
        "workflows": ["Admin and team workflow"],
        "related_modules": ["super_admin", "support"],
        "role_restrictions": "Super-admin only",
        "what_to_document": "Owner-side actions are operational, not client-facing documentation.",
        "common_mistakes": ["Recommending Owner Cockpit as part of standard case-manager workflow"],
        "known_limitations": ["This is distinct from Super Admin and separate from normal org workflow."],
        "caution_notes": ["Never recommend to non-super-admins."],
        "example_questions": ["How do I review platform activity?", "Where is the owner dashboard?"],
    },
    {
        "key": "super_admin",
        "display_name": "Super Admin",
        "routes": ["/super-admin"],
        "aliases": ["super admin", "org control", "organization admin", "platform admin"],
        "who_uses_it": "Platform super-admin users",
        "purpose": "Platform super-admin panel for organization-level controls and billing overrides.",
        "use_when": "Use for organization management and internal billing model administration.",
        "required_or_useful_data": ["Organization detail", "billing draft fields", "org status"],
        "step_by_step": [
            "Open Super Admin if you are a platform super-admin.",
            "Review organization and billing panels.",
            "Use it for internal model changes, not client benefits or standard staff workflow."
        ],
        "workflows": ["Admin and team workflow"],
        "related_modules": ["owner_cockpit", "billing"],
        "role_restrictions": "Super-admin only",
        "what_to_document": "Administrative changes are platform operations, not client documentation.",
        "common_mistakes": ["Confusing Super Admin billing controls with the client Benefits module"],
        "known_limitations": ["The UI explicitly says live payments are not connected even though internal billing model controls are present."],
        "caution_notes": ["Never recommend to normal users or org admins unless they are true super-admins."],
        "example_questions": ["Where do I manage organizations?", "Where do I update internal billing status?"],
    },
    {
        "key": "profile",
        "display_name": "Profile",
        "routes": ["/profile"],
        "aliases": ["profile", "my profile", "account profile", "user profile"],
        "who_uses_it": "All authenticated users",
        "purpose": "User account profile page.",
        "use_when": "Use when checking your own role, account identity, or profile details.",
        "required_or_useful_data": ["Current user profile"],
        "step_by_step": [
            "Open Profile from the account menu or Settings.",
            "Review your displayed account information."
        ],
        "workflows": ["Support, settings, and account workflow"],
        "related_modules": ["settings", "support"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "None for client records; this is account-level.",
        "common_mistakes": ["Using Profile for organization or client updates"],
        "known_limitations": ["Account-level page, not a client workflow surface."],
        "caution_notes": ["Do not conflate user account data with client data."],
        "example_questions": ["Where is my profile?", "How do I check my account page?"],
    },
    {
        "key": "settings",
        "display_name": "Settings",
        "routes": ["/settings"],
        "aliases": ["settings", "account settings", "organization settings", "system status"],
        "who_uses_it": "All authenticated users, with extra admin links",
        "purpose": "Settings hub for account, organization, team, system status, and billing links.",
        "use_when": "Use when navigating to account, organization, team, system status, or billing settings.",
        "required_or_useful_data": ["Current user role", "organization id", "admin status"],
        "step_by_step": [
            "Open Settings.",
            "Choose the relevant section link: Account, Organization, Team Management, SaaS/System Status, Billing, or Support-adjacent items."
        ],
        "workflows": ["Support, settings, and account workflow", "Admin and team workflow"],
        "related_modules": ["profile", "team_management", "supervisor_dashboard", "billing", "support"],
        "role_restrictions": "All authenticated users; admin-only sections appear based on role",
        "what_to_document": "Settings changes are account or org operations, not client notes.",
        "common_mistakes": ["Treating Settings as the place for client data entry"],
        "known_limitations": ["Some sections are placeholders or links into other modules."],
        "caution_notes": ["Respect role-gated sections."],
        "example_questions": ["Where do I go for settings?", "How do I find billing or team links?"],
    },
    {
        "key": "support",
        "display_name": "Support",
        "routes": ["/support"],
        "aliases": ["support", "help", "ticket", "bug report", "feature request", "account issue", "billing question"],
        "who_uses_it": "All authenticated users",
        "purpose": "Help and support ticket page with quick links and intake categories.",
        "use_when": "Use when reporting bugs, account issues, billing questions, or feature requests.",
        "required_or_useful_data": ["Ticket category", "short summary", "general description without client names"],
        "step_by_step": [
            "Open Support.",
            "Choose the ticket category.",
            "Enter a short summary and a general description with no client names, then submit."
        ],
        "workflows": ["Support, settings, and account workflow"],
        "related_modules": ["dashboard", "case_management", "smart_daily", "team_management", "settings"],
        "role_restrictions": "All authenticated users",
        "what_to_document": "Support tickets are operational; do not put client PHI or detailed client narratives here.",
        "common_mistakes": ["Including client names or PHI in support requests"],
        "known_limitations": ["Support is for system help, not case documentation."],
        "caution_notes": ["The UI explicitly tells users to avoid client names; the assistant should repeat that."],
        "example_questions": ["How do I send a support ticket?", "Where do I report a billing question?"],
    },
    {
        "key": "billing",
        "display_name": "Billing",
        "routes": ["/billing"],
        "aliases": ["billing", "plan", "usage", "limits", "stripe billing"],
        "who_uses_it": "All authenticated users with account access; operationally more relevant to admins or org owners",
        "purpose": "Organization plan, usage, and limits page.",
        "use_when": "Use when checking plan status, usage, and billing readiness.",
        "required_or_useful_data": ["Billing status", "plan code", "usage", "stripe capability flags"],
        "step_by_step": [
            "Open Billing from Settings or a direct route.",
            "Review the plan, usage, and billing status cards.",
            "Use checkout or portal only if those capability flags are actually live."
        ],
        "workflows": ["Support, settings, and account workflow"],
        "related_modules": ["settings", "super_admin"],
        "role_restrictions": "All authenticated users with billing access",
        "what_to_document": "Billing is organizational and operational, not client-facing documentation.",
        "common_mistakes": ["Confusing Billing with client benefits or insurance", "Assuming Stripe payments are live"],
        "known_limitations": ["Billing foundation is active, but payments are not connected yet."],
        "caution_notes": ["Do not touch billing behavior in this task; only describe it honestly."],
        "example_questions": ["Where do I see plan usage?", "Is Stripe billing live yet?"],
    },
    {
        "key": "system_integrity",
        "display_name": "System Integrity",
        "routes": ["/system-integrity"],
        "aliases": ["system integrity", "system status", "integrity", "diagnostic"],
        "who_uses_it": "Operational or admin users",
        "purpose": "Diagnostic page for system integrity visibility.",
        "use_when": "Use when checking deeper operational or diagnostic status.",
        "required_or_useful_data": ["System-level status information"],
        "step_by_step": [
            "Open System Integrity for diagnostic review.",
            "Use it as an operational page, not a client workflow module."
        ],
        "workflows": ["Admin and team workflow"],
        "related_modules": ["integration_audit", "settings", "supervisor_dashboard"],
        "role_restrictions": "Operational use; route is present but not primary navigation",
        "what_to_document": "Operational findings belong in internal processes, not client records.",
        "common_mistakes": ["Using diagnostic surfaces as if they were normal case-manager workflow pages"],
        "known_limitations": ["This is not a standard client-care module."],
        "caution_notes": ["Only recommend when the question is clearly operational or diagnostic."],
        "example_questions": ["Where do I check system integrity?", "Is there a diagnostic page?"],
    },
    {
        "key": "integration_audit",
        "display_name": "Integration Audit",
        "routes": ["/integration-audit"],
        "aliases": ["integration audit", "audit page", "route audit", "integration status"],
        "who_uses_it": "Operational or admin users",
        "purpose": "Operational audit view for route and integration checks.",
        "use_when": "Use when reviewing integration or audit-oriented information.",
        "required_or_useful_data": ["Audit tabs", "route list", "test result information"],
        "step_by_step": [
            "Open Integration Audit for the operational review tabs.",
            "Use it for audit or testing context rather than day-to-day client work."
        ],
        "workflows": ["Admin and team workflow"],
        "related_modules": ["system_integrity", "dashboard"],
        "role_restrictions": "Operational use; not a standard nav item",
        "what_to_document": "Operational audit notes belong outside client records.",
        "common_mistakes": ["Treating audit pages as end-user workflow pages"],
        "known_limitations": ["This is a diagnostic or audit surface, not a normal client-care module."],
        "caution_notes": ["Only recommend for operational audit questions."],
        "example_questions": ["Is there an integration audit page?", "Where do I review route audit info?"],
    },
]


MANUAL_BY_KEY: Dict[str, Dict[str, object]] = {entry["key"]: entry for entry in PLATFORM_MANUAL}

